#!/bin/bash

d_flag=''
m_flag=''
fNum=''
p_flag=''
verbose='false'
x_flag=''

print_usage() {
  printf "Usage: ..."
}

# Defining flags
while getopts 'dhmn:pvx' flag; do
  case "${flag}" in
    d) d_flag='true' ;;
    h) print_usage
      exit 0 ;;
    m) m_flag='true' ;;
    n) fNum="${OPTARG}" ;;
    p) p_flag='true' ;;
    x) x_flag='true' ;;
    *) print_usage
      exit 1 ;;
  esac
done

# When -n flag is not used, ask the user to input a value
if [[ $fNum = '' ]]; then
  read -p "Enter number of files to match : " fNum
fi

# Grab output from find command and add each line to array
while IFS= read -r line; do
  list+=( "$line" )
done < <( find -type d )

# Exclude parent directory itself by default. Include with -p flag
if [[ $p_flag != 'true' ]]; then
  unset list[0] # Remove current dir
  list=( "${list[@]}" ) # Re-index array
fi

# Perform action based on number of files found in each directory
listLength=${#list[@]}
  for (( i=0; i<${listLength}; i++ )); do
    listCount+=( $(find "${list[$i]}" -type f | wc -l) )
  done

# loops for processed outputs
# Move formatted -m
if [[ $m_flag = 'true' ]]; then
  for i in "${!list[@]}"; do
    if [[ $x_flag = 'true' ]]; then
      if [[ "${listCount[i]}" = "${fNum}" ]]; then
        output+=( $(echo -n "${list[$i]}" | sed 's|.*|"&\/"* |' ) )
      fi
      printf '%s ' "${output[@]}" | xclip -selection clipboard # Printf used to join the array
    else
      if [[ "${listCount[i]}" = "${fNum}" ]]; then
        echo -n "${list[$i]}" | sed 's|.*|"&\/"* |'
      fi
    fi
  done

# Delete formatted -d
elif [[ $d_flag = 'true' ]]; then
  for i in "${!list[@]}"; do
    if [[ $x_flag = 'true' ]]; then
      if [[ "${listCount[i]}" = "${fNum}" ]]; then
        output+=( $(echo -n "${list[$i]}" | sed 's|.*|"&\/" |' ) )
      fi
      printf '%s ' "${output[@]}" | xclip -selection clipboard # Printf used to join the array
    else
      if [[ "${listCount[i]}" = "${fNum}" ]]; then
        echo -n "${list[$i]}" | sed 's|.*|"&\/" |'
      fi
    fi
  done

# Base format
else
  for i in "${!list[@]}"; do
    if [[ "${listCount[i]}" = "${fNum}" ]]; then
      echo "${list[$i]}"
    fi
  done
fi
