#!/bin/bash

d_flag=''
m_flag=''
fNum=''
p_flag=''
verbose='false'
x_flag=''
dirCount=()
flag=()
list=()
line=()
line2=()
listLength=()
listCount=()
output=()
print_usage=()

print_usage() {
  printf "Usage: ..."
}

# Defining flags
while getopts 'dhmn:pvx' flag; do
  case "${flag}" in
    d) d_flag='true' ;;
    h) print_usage
      exit 0 ;;
    m) m_flag='true' ;;
    n) fNum="${OPTARG}" ;;
    p) p_flag='true' ;;
    x) x_flag='true' ;;
    *) print_usage
      exit 1 ;;
  esac
done

# When -n flag is not used, ask the user to input a value
if [[ $fNum = '' ]]; then
  read -p "Enter number of files to match : " fNum
fi

# Grab output from find command and add each line to array
while IFS= read -r line; do
  list+=( "$line" )
done < <( find -type d )

# Exclude parent directory itself by default. Include with -p flag
if [[ $p_flag != 'true' ]]; then
  unset list[0] # Remove current dir
  list=( "${list[@]}" ) # Re-index array
fi

# Build arrays based on number of files found in each directory
listLength=${#list[@]}
  for (( i=0; i<${listLength}; i++ )); do
    listCount+=( $(find "${list[$i]}" -type f | wc -l) )
  done

# Grab the number of dirs that match the value of fNum
# Might be a better way to do this...
for i in "${!list[@]}"; do
  if [[ "${listCount[i]}" = "${fNum}" ]]; then
    while IFS= read -r line2; do
      dirCount+=( "$line2" )
    done < <( echo "${list[$i]}" )
  fi
done

# loops for processed outputs
# mv formatted -m
if [[ $m_flag = 'true' ]]; then
  for i in "${!list[@]}"; do
    if [[ $x_flag = 'true' ]]; then
      if [[ "${listCount[i]}" = "${fNum}" ]]; then
        output+=( $(echo -n "${list[$i]}" | sed 's|.*|"&\/"* |' ) )
      fi
      printf '%s ' "${output[@]}" | xclip -selection clipboard # Printf used to join the array
    else
      if [[ "${listCount[i]}" = "${fNum}" ]]; then
        echo -n "${list[$i]}" | sed 's|.*|"&\/"* |'
      fi
    fi
  done

# rm formatted -d
elif [[ $d_flag = 'true' ]]; then
  for i in "${!list[@]}"; do
    if [[ $x_flag = 'true' ]]; then
      if [[ "${listCount[i]}" = "${fNum}" ]]; then
        output+=( $(echo -n "${list[$i]}" | sed 's|.*|"&\/" |' ) )
      fi
      printf '%s ' "${output[@]}" | xclip -selection clipboard # Printf used to join the array
    else
      if [[ "${listCount[i]}" = "${fNum}" ]]; then
        echo -n "${list[$i]}" | sed 's|.*|"&\/" |'
      fi
    fi
  done

# Base format
else
  for i in "${!list[@]}"; do
    if [[ $x_flag = 'true' ]]; then
      if [[ "${listCount[i]}" = "${fNum}" ]]; then
        output+=( $(echo "${list[$i]}" ) )
      fi
      echo -n "${output[@]}" | sed -r 's|(.)(./)|\1\n\2|g' | xclip -selection clipboard # still need to find a way to remove whitespace at end of each line
    else
      if [[ "${listCount[i]}" = "${fNum}" ]]; then
        echo "${list[$i]}"
      fi
    fi
  done
fi

if [[ $x_flag = 'true' ]]; then
  echo "${#dirCount[@]} item(s) copied to clipboard"
else
  echo -e "\r\n${#dirCount[@]} item(s) listed"
fi
